### ISSUE TITLE
LED does not illuminate

### ISSUE THREAD

**Issue by uecken** [m5stack/ATOM-ECHO#3]
#include "M5Atom.h"
/* for M5Stack ATOM ECHO */
#define BRIGTHNESS 64
void setup(){
   M5.begin(true, false, true); //Init Atom-Echo
   delay(50);
   M5.dis.drawpix(0, CRGB(BRIGTHNESS, BRIGTHNESS, BRIGTHNESS));
   delay(1000);
}

This code cannot make LED ON.
Both ArduinoIDE and PlatformIO's binary cannot illuminate LED.

**Comment by Tinyu-Zhao** [comment]
It works fine in my environment, please try pulling the latest M5Atom library and try it again.

https://user-images.githubusercontent.com/44396641/179661811-215d6bc3-14a6-4481-9b66-bac3899149d4.MOV
